= Asciidoctor Maven Plugin: Examples

This repository contains a collection of sample projects that demonstrate numerous ways to use the Asciidoctor Maven plugin in a Maven project.

== Getting the examples

Clone the example repository using git:

 $ git clone https://github.com/asciidoctor/asciidoctor-maven-examples

Refer to the README file in each individual project to learn how to run it.

== Example catalog

link:asciidoc-to-html-example/README.adoc[asciidoc-to-html-example] (aka "`The Quickstart`")::
Demonstrates how to convert AsciiDoc to HTML5 using the Asciidoctor Maven plugin.

link:docbook-pipeline-docbkx-example/README.adoc[docbook-pipeline-docbkx-example]::
Demonstrates how to convert AsciiDoc to DocBook and feed it to the DocBook pipeline to generate a PDF using the Asciidoctor and Docbkx Maven plugins.

link:docbook-pipeline-jdocbook-example/README.adoc[docbook-pipeline-jdocbook-example]::
Demonstrates how to convert AsciiDoc to DocBook and feed it to the DocBook pipeline to generate a PDF using the Asciidoctor and jDocBook Maven plugins.

link:asciidoctor-diagram-example/README.adoc[asciidoctor-diagram-example]::
Demonstrates how to integrate Asciidoctor Diagram with the Asciidoctor Maven plugin.

link:asciidoc-to-pdf-example/README.adoc[asciidoc-to-pdf-example]::
Demonstrates how to convert AsciiDoc to PDF using Asciidoctor PDF with the Asciidoctor Maven plugin.

link:asciidoc-site-example/README.adoc[asciidoc-site-example]::
Demonstrates how to process AsciiDoc in a Maven site using the Asciidoctor Maven plugin.

link:asciidoc-multiple-inputs-example/README.adoc[asciidoc-multiple-inputs-example]::
An example project that demonstrates how to convert multiple input AsciiDoc documents to HTML5 and PDF using the
Asciidoctor Maven plugin.

link:java-extension-example/README.adoc[java-extension-example]::
An example project that demonstrates how to create an extension for Asciidoctorj (written in Java) and how to use it in an other documentation Maven module.

== On JRuby dependency

Asciidoctor Maven plugin relies on https://github.com/asciidoctor/asciidoctor[asciidoctor] project to do the actual rendering. This is a Ruby implementation integrated thanks to the http://jruby.org/[JRuby] project, which is a required dependency to run the plugin. The maven plugin provides a default version of the `jruby-complete` artifact to ease its configuration. However, it can be overwritten just adding a custom version in the plugin's dependency section as seen in the following example:
```
    <plugin>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-plugin</artifactId>
        <version>${asciidoctor.maven.plugin.version}</version>
        <dependencies>
            <dependency>
                <groupId>org.jruby</groupId>
                <artifactId>jruby-complete</artifactId>
                <version>${jruby.version}</version>
            </dependency>
         <dependencies>
```  

== Updating Asciidoctor Maven plugin version

In case it is required to test a specific version of the plugin (e.g. local SNAPSHOT version), a tool has been included to update the version in all examples.
To change the plugin's version follow the next steps:

. Set the desired version in the _<asciidoctor.maven.plugin.version>_ property in the _pom.xml_ file located at the root (asciidoctor-maven-examples folder). For instance:

[source,xml,indent=2]
----
<asciidoctor.maven.plugin.version>1.5.2</asciidoctor.maven.plugin.version>
----

[start=2]
. Execute the _validate_ maven goal with the _update-properties_ profile:

[source,indent=2]
----
$ mvn validate -Pupdate-properties
----


== Copyright and Licensing

Copyright (C) 2014 The Asciidoctor Project.
Free use of this software is granted under the terms of the MIT License.

See the link:LICENSE.adoc[] file for details.
