= Asciidoctor Maven Plugin: AsciiDoc to PDF CJK Example
:cn-example-file: README-zh_CN
:jp-example-file: README-jp

An example project that demonstrates how to convert AsciiDoc to PDF using https://github.com/chloerei/asciidoctor-pdf-cjk[asciidoctor-pdf-cjk] and https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic[asciidoctor-pdf-cjk-kai_gen_gothic] resources to properly show CJK (Chinese, Japanese and Korean) characters.

== Usage

[IMPORTANT]
====
Since asciidoctorj-pdf v.1.5.0.beta.2 `asciidoctor-pdf-cjk` and `asciidoctor-pdf-cjk-kai_gen_gothic` gems are no longer compatible.
And while asciidoctor-pdf has evolved to no longer depend on these, the resources contained (theme and fonts) are still of great help to achieve quality documentation for the languages supported.

That's why this example no longer uses the gems, but shows how to import the resources required using maven tools.
We encourage you to experiment with custom themes and additional fonts to suite special needs not supported by this example.
====

Convert the AsciiDoc to PDF using Asciidoctor PDF by invoking the `process-resources` goal (configured as the default goal):

 $ mvn

Open the generated files _target/generated-docs/{cn-example-file}.pdf_ and _target/generated-docs/{jp-example-file}.pdf_ in your PDF viewer to see the generated PDFs.

The examples used are the Chinese and Japanese translations of the Asciidoctor README document (all found link:https://github.com/asciidoctor/asciidoctor/[here]). Contributed respectively by link:https://github.com/diguage[diguage] and link:https://github.com/Mizuho32[Mizuho32].
